#!/bin/sh
NODE_ENV=production node_modules/.bin/webpack
node_modules/.bin/uglifyjs build/js/main.js --mangle --compress warnings=false > build/js/main.min.js
mv build/js/main.min.js build/js/main.js
DEBUG=* node server/server.js

